import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import HeaderAuth from "@/components/header-auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex flex-col items-center min-h-screen">
          <nav className="w-full flex justify-center border-b border-b-foreground/10 h-16">
            <div className="w-full max-w-5xl flex justify-between items-center p-3 px-5 text-sm">
              <div className="flex gap-5 items-center font-semibold">
                <Link href={"/"}>University Library</Link>
                <ul>
                  <li>
                    <Link href="/cart">Cart</Link>
                  </li>
                </ul>
              </div>
              <HeaderAuth />
            </div>
          </nav>
          <div className="w-full flex-auto max-w-5xl p-5">{children}</div>
        </main>
      </body>
    </html>
  );
}
